
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author drlias
 */
public class JPEmpleados extends javax.swing.JPanel {

    Conexion cnx;

    public JPEmpleados(Conexion cnx) {
        initComponents();

        TEmpleados.setRowHeight(50);

        String sql = "SELECT * FROM empleados";
        cnx.entablar(sql, TEmpleados);

        this.cnx = cnx;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEmpleados = new javax.swing.JTable();
        TFNom = new javax.swing.JTextField();
        TFTel = new javax.swing.JTextField();
        TFPuesto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFCodigo = new javax.swing.JTextField();
        BReporte = new javax.swing.JButton();
        BActu = new javax.swing.JButton();
        TFEmpleados = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(97, 199, 195));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Datos del Empleado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("TELÉFONO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("PUESTO:");

        BRegistrar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        BRegistrar.setText("REGISTRAR");
        BRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistrarActionPerformed(evt);
            }
        });

        TEmpleados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TEmpleados.setAlignmentX(1.0F);
        TEmpleados.setAlignmentY(1.0F);
        TEmpleados.setRowMargin(0);
        TEmpleados.setSelectionBackground(new java.awt.Color(204, 255, 204));
        TEmpleados.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TEmpleadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TEmpleados);

        TFNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TFTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TFPuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CODIGO:");

        TFCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        BReporte.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        BReporte.setText("REPORTE");
        BReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReporteActionPerformed(evt);
            }
        });

        BActu.setText("ACTUALIZAR");
        BActu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActuActionPerformed(evt);
            }
        });

        TFEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFEmpleadosKeyPressed(evt);
            }
        });

        jLabel7.setText("BUSCAR");

        BBorrar.setText("Borrar Cliente");
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TFTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(TFNom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TFCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TFPuesto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BRegistrar)
                        .addGap(34, 34, 34)
                        .addComponent(BActu)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(BReporte)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BBorrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TFEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BReporte)
                        .addGap(7, 7, 7)))
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BRegistrar)
                            .addComponent(BActu))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BBorrar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistrarActionPerformed
        String id = TFCodigo.getText();
        String nom = TFNom.getText();
        String tel = TFTel.getText();
        String pue = TFPuesto.getText();

        Empleados em = new Empleados(id, nom, tel, pue);
        
        if (id.equals("")) {
            JOptionPane.showMessageDialog(this, "Hubo un error, intente de nuevo");
        } else if (em.insertar(cnx) == 1){
            JOptionPane.showMessageDialog(this, "Empleado agregado");
            cnx.entablar("SELECT * FROM empleados", TEmpleados);
        } 
    }//GEN-LAST:event_BRegistrarActionPerformed

    private void TEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleadosMousePressed
        int ren = TEmpleados.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) TEmpleados.getModel();

        if (ren >= 0) {
            TFCodigo.setText(modelo.getValueAt(ren, 0).toString());
            TFNom.setText(modelo.getValueAt(ren, 1).toString());
            TFTel.setText(modelo.getValueAt(ren, 2).toString());
            TFPuesto.setText(modelo.getValueAt(ren, 3).toString());

        }
    }//GEN-LAST:event_TEmpleadosMousePressed

    private void BActuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActuActionPerformed
        String id = TFCodigo.getText();
        String nom = TFNom.getText();
        String tel = TFTel.getText();
        String pue = TFPuesto.getText();

        Empleados cl = new Empleados(id, nom, tel, pue);
        if (cl.actualizar(cnx) == 1) {
            String sql = "SELECT * FROM empleados";
            JOptionPane.showMessageDialog(this, "Datos Actualizados");
            cnx.entablar(sql, TEmpleados);

        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar");
        }
    }//GEN-LAST:event_BActuActionPerformed

    private void TFEmpleadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFEmpleadosKeyPressed
        String name = TFEmpleados.getText();
        String sql = "SELECT * FROM empleados WHERE nombree LIKE '%" + name + "%'";
        cnx.entablar(sql, TEmpleados);
    }//GEN-LAST:event_TFEmpleadosKeyPressed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
        int rensel = TEmpleados.getSelectedRow();
        if (rensel > -1) {
            DefaultTableModel datos = (DefaultTableModel) TEmpleados.getModel();
            String codigo = datos.getValueAt(rensel, 0).toString();

            String id = TFCodigo.getText();
            String nom = TFNom.getText();
            String tel = TFTel.getText();
            String pue = TFPuesto.getText();

            Empleados cl = new Empleados(id, nom, tel, pue);
            if (cl.remover(cnx) == 1) {
                String sql = "SELECT * FROM empleados";
                JOptionPane.showMessageDialog(this, "Empleado Borrado");
                cnx.entablar(sql, TEmpleados);

            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Primero selecciona al empleado de la Tabla");

        }
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReporteActionPerformed
        String cla = TFCodigo.getText();
        String reporte = System.getProperty("user.dir") + "/empleados.jasper";

        Map parametros = new HashMap();
        parametros.put("clavePel", cla);

        cnx.ejecutarReporte(reporte, parametros);
    }//GEN-LAST:event_BReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActu;
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BRegistrar;
    private javax.swing.JButton BReporte;
    private javax.swing.JTable TEmpleados;
    private javax.swing.JTextField TFCodigo;
    private javax.swing.JTextField TFEmpleados;
    private javax.swing.JTextField TFNom;
    private javax.swing.JTextField TFPuesto;
    private javax.swing.JTextField TFTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
